import {useState} from 'react';
import {CONTACT,EMAIL_URL,openExternal,copyPublicInfo} from '../../application/externalActions';
import {FOLIO_VERSION} from '../../application/release';
import {Capacitor} from '@capacitor/core';
export function ContactAnva(){
 const [status,setStatus]=useState('');const [fallback,setFallback]=useState(false);
 const go=async(url:string)=>{try{await openExternal(url);setStatus(url===EMAIL_URL?'If no mail window opens, copy the email address below.':'External application requested.');}catch{setStatus('Folio couldn’t open that application. Copy the address and open it yourself.');setFallback(true);}};
 const copy=async(text:string)=>{try{await copyPublicInfo(text===CONTACT.email?"email":"app-info",text);setStatus('Copied.');}catch{setStatus('Copy is unavailable. Select and copy the text below.');setFallback(true);}};
 const info=`Folio ${FOLIO_VERSION}\nPlatform: ${window.folioDesktop?'Windows desktop':Capacitor.getPlatform()}\nSystem: ${navigator.userAgent}`;
 return <section className="card about-card" aria-labelledby="contact-title"><h2 id="contact-title">Help & Contact</h2><p>Questions, bugs or something you’d like us to know? We’d like to hear from you.</p><div className="contact-actions"><button className="btn btn-primary" onClick={()=>go(EMAIL_URL)}>Email ANVA</button><button className="btn btn-secondary" onClick={()=>copy(CONTACT.email)}>Copy email</button><button className="btn btn-secondary" onClick={()=>go(CONTACT.feedback)}>Send feedback</button><button className="btn btn-secondary" onClick={()=>go(CONTACT.website)}>Visit ANVA</button></div><p><strong>{CONTACT.email}</strong> · Email for support or a reply. Use the feedback form for ideas and suggestions.</p><p>When reporting a bug, include Folio version, operating system, what you tried, what happened and useful steps to reproduce it.</p><p className="field-help">Please do not send passwords, recovery credentials, sensitive financial details or private exports unless a safe process has been agreed.</p><button className="btn btn-secondary" onClick={()=>copy(info)}>Copy app information</button><p className="field-help">Folio {FOLIO_VERSION} · {window.folioDesktop?'Windows desktop':Capacitor.getPlatform()}. App information contains no financial or profile data.</p><p role="status">{status}</p>{fallback&&<div><p><code>{CONTACT.website}</code><br/><code>{CONTACT.feedback}</code></p><pre>{info}</pre></div>}</section>;
}
