import { useSession } from '../../application/FolioProvider';
import { todayKey } from '../../domain/dates';
import { money, monthLabel, dateLabel } from '../presentation';
import { navigate } from '../navigation';

export function DashboardScreen() {
  const { controller, controllerRevision, saveStatus } = useSession();
  void controllerRevision;
  if (!controller) return null;
  const data = controller.snapshot;
  const balances = controller.getAccountBalances();
  const month = controller.getCurrentMonthKey();
  const cash = controller.getMonthlyCashFlow(month);
  const recent = controller.getRecentTransactions(5);
  const goals = data.goals.filter(g=>g.active).slice(0,3);
  const goalsWithoutDate = data.goals.filter(g=>g.active).some(g=>{const p=controller.projectGoal(g.id,todayKey(),0);return p.remaining>0&&!p.projectedTargetMonth;});
  const name = (id:string) => data.accounts.find(a=>a.id===id)?.name ?? 'Unknown account';
  const empty = !data.accounts.length;
  return <div className="overview">
    <header className="screen-header"><div><p className="eyebrow">Your financial notebook</p><h1 className="screen-title">Dashboard</h1><p className="screen-sub">{monthLabel(month)} · Recorded so far</p></div><button className="btn btn-primary" onClick={()=>navigate(empty?'accounts':'transactions',empty?'create':'create')}>{empty?'Add an account':'Record transaction'}</button></header>
    {(empty || !data.txns.length) && <section className="setup-path"><h2>Start with what you know</h2><p>A profile is your separate, encrypted financial record on this device.</p><ol><li><button className="link-btn" onClick={()=>navigate('accounts','create')}>Add an account</button><span>{data.accounts.length?'Added':'Choose your starting balance'}</span></li><li><button className="link-btn" onClick={()=>navigate('transactions','create')}>Record a transaction</button><span>Income, an expense or a transfer</span></li><li><button className="link-btn" onClick={()=>navigate('settings','backup')}>Create a backup</button><span>Keep a copy outside this device</span></li></ol></section>}
    {!empty && <>
      <section className="overview-snapshot"><div className="stat"><p className="eyebrow stat-label">Active account total</p><p className="headline-amount stat-value">{money(balances.consolidated)}</p><p className="field-help">Opening balances plus included transactions across active accounts. Separate Debt plans are not deducted; this is not net worth or spendable funds.</p></div><div className="month-metrics"><h2>Recorded this month</h2><dl className="metric-list"><div className="stat"><dt className="stat-label">Recorded income</dt><dd className="stat-value">{money(cash.actual.income)}</dd></div><div className="stat"><dt className="stat-label">Recorded expenses</dt><dd className="stat-value">{money(cash.actual.expense)}</dd></div><div className="stat"><dt className="stat-label">Recorded surplus</dt><dd className="stat-value">{money(cash.actual.net)}</dd></div></dl><p className="field-help">Month-to-date income less expenses, not verified savings.</p></div></section>
      {(cash.actual.net<0||goalsWithoutDate) && <section className="notebook-section"><h2>Figures to review</h2>{cash.actual.net<0&&<p>Recorded expenses exceed income so far this month. Your records may be incomplete. <button className="link-btn" onClick={()=>navigate('transactions')}>Review recorded transactions</button></p>}{goalsWithoutDate&&<p>Some active goal completion dates cannot be calculated. <button className="link-btn" onClick={()=>navigate('goals')}>Review goal assumptions</button></p>}</section>}
      <div className="overview-columns"><section className="notebook-section"><div className="section-heading"><h2>Accounts</h2><button className="link-btn" onClick={()=>navigate('accounts')}>View accounts</button></div><div className="list">{balances.accounts.map(a=><button className="list-row" key={a.id} onClick={()=>navigate('transactions','account',a.id)}><span className="list-row-main"><strong>{a.name}</strong><span className="record-meta">{a.type}</span></span><span className="amount">{money(balances.balances.get(a.id) ?? 0)}</span></button>)}</div></section>
      <section className="notebook-section"><div className="section-heading"><h2>Scheduled this month</h2><button className="link-btn" onClick={()=>navigate('recurring')}>Review schedules</button></div><dl className="metric-list"><div><dt>Expected income</dt><dd>{money(cash.committed.income)}</dd></div><div><dt>Expected expenses</dt><dd>{money(cash.committed.expense)}</dd></div></dl><p className="field-help">Whole-month schedules, separate from recorded transactions. These figures do not tell you what is paid or unpaid.</p>{saveStatus==='error' && <p role="alert">Your changes need attention. Review the save message before continuing.</p>}</section></div>
      {goals.length > 0 && <section className="notebook-section"><div className="section-heading"><h2>Active goals</h2><button className="link-btn" onClick={()=>navigate('goals')}>Review all goals</button></div><div className="overview-goals">{goals.map(g=>{const p=controller.projectGoal(g.id,todayKey(),0);return <button className="goal-preview" key={g.id} onClick={()=>navigate('goals')}><strong>{g.name}</strong><span>{money(p.remaining)} remaining</span><span className="record-meta">{p.projectedTargetMonth?monthLabel(p.projectedTargetMonth):'Completion cannot be calculated'}</span>{g.linkedAccountId && <span className="record-meta">Linked balance may overlap other goals</span>}</button>;})}</div><p className="field-help">Contribution comparisons use the amount you enter in Goals; no shared available amount is assumed.</p></section>}
    </>}
    <section className="notebook-section"><div className="section-heading"><h2>Recent transactions</h2><button className="link-btn" onClick={()=>navigate('transactions')}>View history</button></div>{recent.length ? <div className="list">{recent.map(t=><button key={t.id} className="list-row" onClick={()=>navigate('transactions','edit',t.id)}><span className="list-row-main"><strong>{t.type==='transfer'?`${name(t.accountId)} → ${name(t.toAccountId!)}`:data.categories.find(c=>c.id===t.categoryId)?.name ?? t.type}</strong><span className="record-meta">{dateLabel(t.date)} · {t.type} · {name(t.accountId)}</span></span><span className="amount">{money(t.amount)}</span></button>)}</div> : <div className="empty-state"><h3>No transactions yet</h3><p>Record what happened to start building your financial picture.</p><button className="btn btn-secondary" onClick={()=>navigate('transactions','create')}>Record a transaction</button></div>}</section>
  </div>;
}
