import {useEffect,useRef,useState} from 'react';
import {HELP,searchHelp} from '../../application/helpContent';
import {useProduct} from '../../application/productNavigation';
import {ContactAnva} from '../components/ContactAnva';
export function HelpScreen({initialArticle}:{initialArticle?:string}){
 const product=useProduct();const [query,setQuery]=useState('');const [category,setCategory]=useState('All');const [selected,setSelected]=useState(initialArticle);const last=useRef<HTMLButtonElement|null>(null);
 const results=searchHelp(query,category);const article=HELP.find(a=>a.id===selected);
 useEffect(()=>{if(article)document.getElementById('help-article-title')?.focus();},[selected]);
 return <div className="help-screen"><header className="screen-header"><div><h1 className="screen-title">Help & FAQ</h1><p className="screen-sub">A small guide to your Folio. Search works entirely on this device.</p></div></header>{article?<article className="card help-article"><button className="link-btn" onClick={()=>{setSelected(undefined);requestAnimationFrame(()=>document.querySelector<HTMLElement>(`[data-article="${last.current?.dataset.article}"]`)?.focus());}}>Back to questions</button><h2 id="help-article-title" tabIndex={-1}>{article.title}</h2><p className="help-answer">{article.answer}</p>{article.detail&&<p>{article.detail}</p>}{article.exampleScreen&&<button className="btn btn-secondary" onClick={()=>product.openExample(article.exampleScreen)}>Try this in the Example Profile</button>}{article.related&&<div><h3>Related questions</h3>{article.related.map(id=><button className="link-btn" key={id} onClick={()=>setSelected(id)}>{HELP.find(a=>a.id===id)?.title}</button>)}</div>}</article>:<><div className="help-search"><label className="field">Search Help<input className="input" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try backups, goals or password"/></label><label className="field">Category<select className="select" value={category} onChange={e=>setCategory(e.target.value)}>{['All',...new Set(HELP.map(a=>a.category))].map(c=><option key={c}>{c}</option>)}</select></label></div><p role="status">{results.length} questions found</p><div className="help-results">{results.map(a=><button className="help-result" key={a.id} data-article={a.id} onClick={e=>{last.current=e.currentTarget;setSelected(a.id);}}><span className="eyebrow">{a.category}</span><strong>{a.title}</strong><span>{a.answer}</span></button>)}</div>{!results.length&&<div className="empty-state"><h2>No matching questions</h2><p>Try a shorter phrase or another category. You can also contact ANVA below.</p><button className="btn btn-secondary" onClick={()=>{setQuery('');setCategory('All');}}>Show all questions</button></div>}</>}<ContactAnva/></div>;
}
