// @vitest-environment jsdom
import {afterEach,describe,it,expect,vi} from 'vitest';
import {cleanup,render,screen,fireEvent,waitFor,within} from '@testing-library/react';
import 'fake-indexeddb/auto';
import App from '../../src/App';
import {ExampleRepository,EXAMPLE_ID,EXAMPLE_PASSWORD} from '../../src/application/exampleProfile';
import {ProfileRepository} from '../../src/persistence/profileRepository';
import {createEmptyProfileData} from '../../src/application/profileData';
import {ProfileAvatar} from '../../src/ui/components/ProfileAvatar';
import {ContactAnva} from '../../src/ui/components/ContactAnva';
import {prepareProfilePhoto} from '../../src/application/profilePhoto';
let counter=0;const repos:ProfileRepository[]=[];
function setup(){const personal=new ProfileRepository({dbName:'completion-ui-personal-'+counter++});const example=new ExampleRepository('completion-ui-example-'+counter++);repos.push(personal,example);return {personal,example};}
afterEach(async()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();localStorage.clear();while(repos.length){const repo=repos.pop()!;await repo.close();await repo.deleteDatabase();}});
const visit=(name:string)=>fireEvent.click(screen.getAllByRole('button',{name}).find(b=>b.className.includes('nav-item'))!);
describe('Folio front door and sandbox',()=>{
 it('always greets fresh and returning users, then preselects the sole profile without unlocking',async()=>{
  const {personal,example}=setup();const item=await personal.createProfile({label:'Personal',password:'pw',data:createEmptyProfileData()});
  const app=render(<App personalRepo={personal} exampleRepo={example}/>);await screen.findByRole('button',{name:'OPEN YOUR FOLIO'});expect(screen.queryByLabelText('Password')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'OPEN YOUR FOLIO'}));await screen.findByText('Select a profile');await waitFor(()=>expect(document.querySelector('.profile-row-btn')?.getAttribute('aria-pressed')).toBe('true'));expect((await personal.listProfiles())[0].profileId).toBe(item.profileId);expect(screen.queryByRole('heading',{name:'Dashboard'})).toBeNull();
  fireEvent.change(screen.getByLabelText('Password'),{target:{value:'pw'}});fireEvent.click(screen.getByRole('button',{name:'Unlock'}));await screen.findByRole('heading',{name:'Dashboard'});fireEvent.click(screen.getAllByRole('button',{name:'Lock'})[0]);await screen.findByText('Select a profile');expect(screen.queryByRole('button',{name:'OPEN YOUR FOLIO'})).toBeNull();app.unmount();render(<App personalRepo={personal} exampleRepo={example}/>);await screen.findByRole('button',{name:'OPEN YOUR FOLIO'});
 });
 it('opens a mutable passwordless example, persists edits, and replaces backup controls with honest guidance',async()=>{
  const {personal,example}=setup();render(<App personalRepo={personal} exampleRepo={example}/>);fireEvent.click(await screen.findByRole('button',{name:'EXPLORE EXAMPLE PROFILE'}));await screen.findByRole('heading',{name:'Dashboard'});expect(screen.getByText('EXAMPLE · SAMPLE DATA')).toBeTruthy();expect(screen.queryByLabelText('Password')).toBeNull();visit('Settings');await screen.findByText('Profile identity');expect(screen.queryByRole('button',{name:'Create encrypted backup'})).toBeNull();expect(screen.queryByLabelText('Restore backup')).toBeNull();expect(screen.getByRole('button',{name:'Export transactions'})).toBeTruthy();
  fireEvent.click(screen.getByRole('button',{name:'Rename'}));fireEvent.change(await screen.findByLabelText('New name'),{target:{value:'My sandbox experiment'}});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Rename'}));await waitFor(async()=>expect((await example.listProfiles())[0].label).toBe('My sandbox experiment'));expect(await personal.listProfiles()).toEqual([]);
 });
 it('loads explicit fictional Health and Planner figures only in example mode',async()=>{
  const {personal,example}=setup();render(<App personalRepo={personal} exampleRepo={example}/>);fireEvent.click(await screen.findByRole('button',{name:'EXPLORE EXAMPLE PROFILE'}));await screen.findByRole('heading',{name:'Dashboard'});visit('Health checks');expect((screen.getByLabelText('Liquid funds') as HTMLInputElement).value).toBe('');fireEvent.click(screen.getByRole('button',{name:'Try example figures'}));expect((screen.getByLabelText('Monthly income') as HTMLInputElement).value).toBe('52000');visit('Planner');fireEvent.click(screen.getByRole('button',{name:'Try example figures'}));visit('Health checks');expect((screen.getByLabelText('Liquid funds') as HTMLInputElement).value).toBe('');expect((await example.unlockProfile(EXAMPLE_ID,EXAMPLE_PASSWORD)).data).not.toHaveProperty('monthlyIncome');
 });
 it('keeps Help available while locked, searches locally, opens an article and restores focus',async()=>{
  const {personal,example}=setup();render(<App personalRepo={personal} exampleRepo={example}/>);fireEvent.click(await screen.findByRole('button',{name:'Help & FAQ'}));const search=screen.getByLabelText('Search Help');fireEvent.change(search,{target:{value:'recurring'}});const question=screen.getByRole('button',{name:/What is the difference between Recorded and Scheduled/});fireEvent.click(question);expect(screen.getByRole('heading',{name:'What is the difference between Recorded and Scheduled?'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Back to questions'}));await waitFor(()=>expect((document.activeElement as HTMLElement).dataset.article).toBe('recorded-scheduled'));fireEvent.change(screen.getByLabelText('Search Help'),{target:{value:'unfindablexyz'}});expect(screen.getByText('0 questions found')).toBeTruthy();expect(screen.getByRole('button',{name:'Email ANVA'})).toBeTruthy();
 });
 it('blocks sandbox entry if the active personal session cannot flush',async()=>{
  const {personal,example}=setup();const data=createEmptyProfileData();await personal.createProfile({label:'Personal',password:'pw',data});render(<App personalRepo={personal} exampleRepo={example}/>);fireEvent.click(await screen.findByRole('button',{name:'OPEN YOUR FOLIO'}));await screen.findByLabelText('Password');fireEvent.change(screen.getByLabelText('Password'),{target:{value:'pw'}});fireEvent.click(screen.getByRole('button',{name:'Unlock'}));await screen.findByRole('heading',{name:'Dashboard'});visit('Accounts');fireEvent.click(screen.getByRole('button',{name:'Add account'}));fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Unflushed'}});fireEvent.change(screen.getByLabelText('Opening balance'),{target:{value:'100'}});vi.spyOn(personal,'saveUnlockedProfile').mockRejectedValue(new Error('Disk unavailable'));fireEvent.click(screen.getByRole('button',{name:'Create'}));visit('Help & FAQ');fireEvent.change(screen.getByLabelText('Search Help'),{target:{value:'How do Goals work'}});fireEvent.click(screen.getByRole('button',{name:/How do Goals work/}));fireEvent.click(screen.getByRole('button',{name:'Try this in the Example Profile'}));await screen.findByText(/Your current profile stayed open/);expect(screen.queryByText('EXAMPLE · SAMPLE DATA')).toBeNull();expect(await example.listProfiles()).toEqual([]);
 });
});
describe('Profile identity and public contact',()=>{
 it('shows initials, uses the selected photo, handles broken images, replacement and removal',()=>{const app=render(<ProfileAvatar name="Asha Rao"/>);expect(screen.getByLabelText("Asha Rao's initials").textContent).toBe('AR');app.rerender(<ProfileAvatar name="Asha Rao" photo="data:image/jpeg;base64,aA=="/>);fireEvent.error(screen.getByAltText("Asha Rao's profile"));expect(screen.getByLabelText("Asha Rao's initials")).toBeTruthy();app.rerender(<ProfileAvatar name="Asha Rao" photo="data:image/jpeg;base64,bA=="/>);expect((screen.getByAltText("Asha Rao's profile") as HTMLImageElement).src).toContain('bA==');app.rerender(<ProfileAvatar name="Asha Rao"/>);expect(screen.queryByRole('img')).toBeNull();});
 it('provides copy email and safe app information when opening mail fails',async()=>{
  vi.stubGlobal('folioDesktop',undefined);const openExternal=vi.fn().mockRejectedValue(new Error('No mail client'));Object.defineProperty(window,'folioDesktop',{value:{openExternal},configurable:true});const writeText=vi.fn().mockResolvedValue(undefined);Object.defineProperty(navigator,'clipboard',{value:{writeText},configurable:true});render(<ContactAnva/>);fireEvent.click(screen.getByRole('button',{name:'Email ANVA'}));await screen.findByText(/Copy the address/);expect(openExternal).toHaveBeenCalledWith('mailto:Anvahq@gmail.com');fireEvent.click(screen.getByRole('button',{name:'Copy email'}));await waitFor(()=>expect(writeText).toHaveBeenCalledWith('Anvahq@gmail.com'));fireEvent.click(screen.getByRole('button',{name:'Copy app information'}));await waitFor(()=>expect(writeText.mock.calls.at(-1)?.[0]).toMatch(/Folio 1.0.0/));expect(writeText.mock.calls.at(-1)?.[0]).not.toMatch(/profile|balance|password/i);delete window.folioDesktop;
 });
 it('rejects corrupt photos and releases the temporary object URL',async()=>{
  const revoke=vi.fn();Object.defineProperty(URL,'createObjectURL',{value:()=> 'blob:local-test',configurable:true});Object.defineProperty(URL,'revokeObjectURL',{value:revoke,configurable:true});vi.stubGlobal('Image',class{src='';decode(){return Promise.reject(new Error('Corrupt'));}});await expect(prepareProfilePhoto(new File(['bad'],'broken.jpg',{type:'image/jpeg'}))).rejects.toThrow(/couldn’t read/);expect(revoke).toHaveBeenCalledWith('blob:local-test');
 });
});
