export type HelpArticle={id:string;category:string;title:string;answer:string;detail?:string;related?:string[];exampleScreen?:string};
const article=(id:string,category:string,title:string,answer:string,detail?:string,exampleScreen?:string):HelpArticle=>({id,category,title,answer,detail,exampleScreen});
export const HELP:HelpArticle[]=[
 article('start','Getting Started','What is Folio?','Your private financial notebook for recording money, understanding your records and planning with explicit assumptions.','Create a profile for your own finances, or explore Meera’s fictional Example Profile without a password.'),
 article('currency','Getting Started','What currency does Folio support?','Folio v1 uses Indian rupees (INR).','Amounts use paise internally. Folio does not convert currencies or combine accounts in different currencies.'),
 article('create','Profiles & Security','How do I create or switch profiles?','Open your Folio, then create a profile or select one to unlock.','Each personal profile has its own password. To switch, use Switch profile or Lock, then choose another profile.'),
 article('password','Profiles & Security','What if I forget my password? Can ANVA reset it?','ANVA cannot reset or recover your profile password. There is no recovery key in Folio v1.','An encrypted backup still needs the password used when that backup was made. Keep both safe. You can delete an inaccessible profile with explicit name confirmation, but deletion does not recover its records.'),
 article('password-change','Profiles & Security','What happens when I change my password?','Your current local vault is re-encrypted and locked. Unlock it with the new password.','Older backups still need their old password. Create a new encrypted backup after changing your password.'),
 article('photo','Profiles & Security','Where is my profile photo stored?','Your resized photo is part of your encrypted personal profile and encrypted backup.','The locked picker shows initials, not your private photo. Pictures are processed on your device, center-cropped and reduced to 256 pixels. No image is uploaded.'),
 article('lock','Profiles & Security','Why did Folio lock?','Folio can lock after inactivity. Choose the interval in Settings.','Lock saves recorded changes first. Unsubmitted form entries are not durable drafts. Never treat an open form as a saved transaction.'),
 article('opening','Accounts','What is an opening balance?','The amount in an account immediately before the transactions you start recording in Folio.','If your opening balance already includes an old transaction, do not record that transaction again: it would count twice. Credit account balances represent money owed as negative amounts.', 'accounts'),
 article('balances','Accounts','Is the active account total my net worth?','No. It sums opening balances and included transactions across active accounts.','Separate manually maintained Debt plans are not deducted. The total is not a verified net worth or a safe-to-spend figure.'),
 article('archive-account','Accounts','What happens when I archive an account?','It stays in your records but leaves the active account total and new-entry choices.','Existing history remains. Check the screen’s active/all scope when comparing totals.'),
 article('entry','Transactions','How do I record several transactions quickly?','Use Save and add another. It keeps the date, transaction type and source account for the next entry.','Enter amount, category and note again. The last-used account and filters are session preferences; they are forgotten after locking.', 'transactions'),
 article('transfers','Transactions','How do transfers affect income and expenses?','Transfers move money between your accounts without creating income or spending.','Use Transfer for savings moves or cash withdrawals between accounts you track. Transfers are excluded from cash-flow income/expense totals.', 'transactions'),
 article('exclude','Transactions','What does excluding a transaction do?','It retains the record but removes its effect from calculations.','Use Show excluded to find it and include it again. This is not permanent deletion.'),
 article('recorded-scheduled','Scheduled / Recurring','What is the difference between Recorded and Scheduled?','Recorded transactions represent money you entered as having moved. Schedules represent separate expectations.','Adding a schedule does not generate a transaction. Scheduled figures do not tell you what has been paid or remains unpaid.', 'recurring'),
 article('schedules','Scheduled / Recurring','Do schedules change balances automatically?','No. Record the actual movement separately when it happens.','Monthly summaries show expected commitments over the whole month, separately from recorded activity.'),
 article('debt','Debt','Why does recording a debt payment not change Debt?','Debt balances are manually maintained planning records.','Record the actual payment in Transactions and update the Debt plan separately. A plan may describe an obligation also represented by a credit account: do not subtract both as if they were distinct debts.', 'debts'),
 article('debt-payoff','Debt','Why can’t Folio calculate a payoff date?','The supplied balance, interest and payment may not produce a supported payoff projection.','A payment may be too small to cover interest. Read the explanation and check the inputs. Estimates are not lender statements.'),
 article('goals','Goals','How do Goals work?','A goal compares a target with a linked account balance or a manually entered saved amount.','Choose a monthly contribution or target date. Linked goals can overlap because each reads the whole linked account balance; Folio does not reserve that money exclusively.', 'goals'),
 article('goal-date','Goals','What does the projected completion date mean?','An estimate using your supplied saved amount, contribution and optional growth assumption.','The existing model counts its first projected contribution this month. Intended contributions are not confirmed actual savings. Returns are assumptions, not guarantees.'),
 article('goal-demand','Goals','Can all my goals fit my monthly saving amount?','All active goals together compares their calculable monthly requirements with the amount you explicitly enter.','If any requirement cannot be calculated, Folio cannot claim that the whole plan fits. The comparison does not allocate money or coordinate other planning screens.'),
 article('health','Health','What does Health evaluate? Is it financial advice?','It compares the figures you supply with chosen emergency-buffer, debt/income and recorded-surplus targets.','There is no overall Health Score or verified completeness assessment. Inputs are temporary. No Debt records does not prove that you have no debt. These checks are planning aids, not financial advice.', 'health'),
 article('unknown','Health','Why does Folio say Not supplied or Cannot calculate?','Some results need inputs you have not provided, or the inputs do not support that calculation.','Unknown is different from a real zero. Month-to-date helper values may not describe a typical month.'),
 article('planner','Planner','Does Planner change my real records?','No. It evaluates a temporary what-if using the costs, funds, reserve and surplus you enter.','It does not create transactions, reserve funds, modify goals or guarantee affordability. Its assumptions are not shared or saved as scenarios.', 'planner'),
 article('reports','Reports','What are Reports based on?','Included transactions and separate schedules in the chosen period.','Transfers do not count as income/expenses. Missing records can make reports incomplete. Folio does not verify them against a bank.', 'reports'),
 article('empty-month','Reports','Why does a month have no recorded transactions?','No included transactions were recorded for that month.','This does not establish that nothing happened or that your spending was zero.'),
 article('backup','Backups & Restore','How do encrypted backups work?','Create encrypted backup in Settings, finish the save/share action, and verify that you have a .folio file.','The vault and authoritative profile photo remain encrypted. Profile names and backup metadata are readable. Backup export flushes current recorded changes first.'),
 article('backup-storage','Backups & Restore','Where should I keep backups?','Save a current encrypted backup somewhere you control outside Folio’s app storage.','Keep a separate copy if the device is lost. On Android, the share cache is temporary and cleared at a later app start. A share dialog opening does not prove that a backup was saved.'),
 article('move','Backups & Restore','How do I move Folio to another device?','Export an encrypted backup, transfer the file safely, then restore it on the other device.','Open your Folio → Restore from backup → select the .folio file. Unlock with the password used for that backup. Existing matching profiles require explicit replacement confirmation.'),
 article('replace','Backups & Restore','Will restoring a backup overwrite another profile?','A matching profile ID requires explicit profile-name confirmation before replacement.','Replacement overwrites that profile’s current record. Save a backup of the current record first. A different profile ID is imported separately.'),
 article('csv','CSV / Exports','Are CSV exports private backups?','No. CSV exports are readable plaintext tables, not encrypted restorable vaults.','Anyone with the file can read it. Folio v1 does not import CSV. Use an encrypted .folio backup to move or preserve a personal profile.'),
 article('export-finish','CSV / Exports','Why does Folio say export requested?','Folio can start the platform download/share flow but cannot verify where you saved the file.','Finish the platform action and check the resulting file. Canceling that action does not save it.'),
 article('example','Example Profile','What is the Example Profile? Is Meera real?','Meera Rao and her financial life are fictional sample data.','The example is a passwordless editable sandbox kept separately from personal profiles. Do not enter private financial information in it.'),
 article('example-edit','Example Profile','Can I modify or break the Example Profile?','Yes. Add, edit or exclude records and change its plans freely. Experiments persist when you reopen it.','The persistent EXAMPLE · SAMPLE DATA indicator distinguishes it from your own finances.', 'dashboard'),
 article('example-reset','Example Profile','How do I reset, delete or restore the example?','Use Example controls in Settings. Reset restores the current canonical dataset after confirmation.','Delete removes your experiments and does not respawn the example on launch. Restore Example Profile on Welcome or the profile gate recreates it explicitly. These actions target only the sandbox.'),
 article('example-exports','Example Profile','Can I export Example data?','CSV exports work and their filenames start with FOLIO-EXAMPLE.','Private encrypted backup/import controls are unavailable in the sandbox. Its built-in compatibility credential is public and does not provide privacy. Reset/Restore recreates canonical data, not your experiments.'),
 article('example-figures','Example Profile','What are Try example figures?','Explicit fictional assumptions you can load into Health or Planner and then change.','They remain temporary and are available only in Example mode. They do not change or populate personal planning inputs.'),
 article('storage','Privacy & Data Storage','Where is my data? Does ANVA receive it?','Personal financial records are encrypted in local app/browser storage. ANVA does not receive your Folio records.','Profile names are readable so the picker can list them. Folio has no telemetry or bank sync. External contact links open another application but do not attach financial records.'),
 article('bank','Privacy & Data Storage','Why no bank login or online account?','Folio is a manual-entry application that works with records you control on your device.','No bank synchronization or cloud financial account is required or offered.'),
 article('uninstall','Privacy & Data Storage','What happens if I uninstall or clear storage?','You can lose local profiles. Save an encrypted backup outside the app first.','Android uninstall removes app data. The Windows installer is configured to preserve app data on uninstall, but manual clearing, device loss or storage damage can still erase it. Browser storage is tied to its browser and site origin.'),
 article('save-error','Troubleshooting','What should I do if Folio can’t save?','Keep Folio open, read the explanation and resolve the problem before leaving.','Another window or a restored backup can cause a save conflict. Do not overwrite blindly. Preserve your work through the offered safe options. A Saving state is not a Saved confirmation.'),
 article('storage-error','Troubleshooting','Why can’t Folio open local storage?','The browser or device may be blocking storage, or another window may be interfering.','Do not clear app storage as a first troubleshooting step. Check storage availability and contact ANVA with the safe app information and error details.'),
 article('contact','Contact & Support','How do I report a bug or ask for help?','Email ANVA for a reply, or use Send feedback for suggestions.','Include Folio version, operating system, what you tried, what happened and reproduction steps. Do not send passwords, recovery credentials, sensitive financial information or private exports unless a safe process has been agreed.'),
 article('support','Contact & Support','Do donations unlock features?','No. Folio is free to use and financial support is optional.','Help & Contact is separate from Support ANVA. There are no donation prompts or locked features.')
];
HELP.find(a=>a.id==='goals')!.related=['goal-date','goal-demand'];
HELP.find(a=>a.id==='backup')!.related=['backup-storage','move','password-change'];
const synonyms:Record<string,string>={login:'unlock',signin:'unlock',recurring:'scheduled',archive:'exclude',loan:'debt',recovery:'password',demo:'example',sample:'example',rupees:'currency'};
export function searchHelp(query:string,category='All'){
 const terms=query.trim().toLowerCase().split(/\s+/).filter(Boolean).map(t=>[t,synonyms[t]].filter(Boolean));
 return HELP.filter(a=>(category==='All'||a.category===category)&&terms.every(options=>options.some(t=>`${a.title} ${a.answer} ${a.detail??''} ${a.category}`.toLowerCase().includes(t))));
}
