import {useEffect,useMemo,useRef,useState} from 'react';
import {RepoProvider,SessionProvider,useSession} from './application/FolioProvider';
import {ProfileRepository} from './persistence/profileRepository';
import {ExampleRepository,EXAMPLE_ID,EXAMPLE_PASSWORD,exampleDeleted} from './application/exampleProfile';
import {ProductContext,guardedTransition} from './application/productNavigation';
import {ProfileGate} from './ui/profile/ProfileGate';
import {AppShell} from './ui/AppShell';
import {WelcomeScreen} from './ui/WelcomeScreen';
import {HelpScreen} from './ui/screens/HelpScreen';
import {AboutFolio} from './ui/components/AboutFolio';
import {listenForAndroidBack} from './application/nativeNavigation';
type Start={mode:'personal'|'example';page:'welcome'|'profiles';screen?:string};
export default function App({personalRepo,exampleRepo}:{personalRepo?:ProfileRepository;exampleRepo?:ExampleRepository}={}){
 const [start,setStart]=useState<Start>({mode:'personal',page:'welcome'});
 const sandbox=useMemo(()=>exampleRepo??new ExampleRepository(),[exampleRepo]);
 return <RepoProvider key={start.mode} repo={start.mode==='example'?sandbox:personalRepo}><SessionProvider><FrontDoor start={start} change={setStart} sandbox={sandbox}/></SessionProvider></RepoProvider>;
}
function FrontDoor({start,change,sandbox}:{start:Start;change:(start:Start)=>void;sandbox:ExampleRepository}){
 const {controller,lock,unlock}=useSession();const [page,setPage]=useState<'welcome'|'profiles'|'help'|'about'>(start.page);const [article,setArticle]=useState<string>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const previous=useRef<'welcome'|'profiles'>('welcome');const entering=useRef(false);const example=start.mode==='example';
 const enter=async(screen?:string,restore=false)=>{if(entering.current)return;entering.current=true;setBusy(true);setError('');try{await sandbox.ensure(restore);await unlock(EXAMPLE_ID,EXAMPLE_PASSWORD);if(screen)requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent('folio:navigate',{detail:{screen}})));}catch(e){setError(e instanceof Error?e.message:'Could not open the Example Profile.');}finally{setBusy(false);entering.current=false;}};
 useEffect(()=>{if(example)void enter(start.screen,true);},[]);
 const transition=(next:Start)=>guardedTransition(()=>{void(async()=>{setBusy(true);setError('');try{await lock();if(next.mode!==start.mode)change(next);else setPage(next.page);}catch{setError('Folio couldn’t save your changes. Your current profile stayed open. Resolve the save error before switching.');}finally{setBusy(false);}})();});
 const publicPage=(next:'help'|'about',id?:string)=>guardedTransition(()=>{if(controller){window.dispatchEvent(new CustomEvent('folio:navigate',{detail:{screen:next,article:id}}));return;}previous.current=page==='profiles'?'profiles':'welcome';setArticle(id);setPage(next);});
 const product={example,openExample:(screen?:string)=>{if(example){guardedTransition(()=>{if(controller&&screen)window.dispatchEvent(new CustomEvent('folio:navigate',{detail:{screen}}));else void enter(screen,exampleDeleted());});}else transition({mode:'example',page:'profiles',screen});},openWelcome:()=>transition({mode:'personal',page:'welcome'}),openProfiles:()=>transition({mode:'personal',page:'profiles'}),openHelp:(id?:string)=>publicPage('help',id),openAbout:()=>publicPage('about'),resetExample:async()=>{setBusy(true);setError('');try{await lock();await sandbox.reset();await unlock(EXAMPLE_ID,EXAMPLE_PASSWORD);setNotice('Example Profile reset.');}catch(e){setError('Could not reset the Example Profile. '+(e instanceof Error?e.message:''));throw e;}finally{setBusy(false);}},deleteExample:async()=>{setBusy(true);setError('');try{await lock();await sandbox.remove();change({mode:'personal',page:'welcome'});}catch(e){setError('Could not delete the Example Profile. '+(e instanceof Error?e.message:''));throw e;}finally{setBusy(false);}}};
 useEffect(()=>{if(controller)return;let disposed=false;let remove:(()=>Promise<void>)|undefined;void listenForAndroidBack(()=>{if(page==='help'||page==='about'){setPage(previous.current);}else if(page==='profiles'){if(document.querySelector('[role=dialog]')){document.querySelector<HTMLButtonElement>('[role=dialog] button[aria-label=Close]')?.click();}else if(document.querySelector('[data-creating-profile]')){document.querySelector<HTMLButtonElement>('[data-create-back]')?.click();}else if(example){change({mode:'personal',page:'welcome'});}else setPage('welcome');}else{void import('@capacitor/app').then(({App})=>App.exitApp());}}).then(handle=>{if(disposed)void handle?.remove();else if(handle)remove=()=>handle.remove();});return()=>{disposed=true;void remove?.();};},[page,controller,example]);
 useEffect(()=>{if(busy)return;const heading=document.querySelector<HTMLElement>('main h1,.auth-card h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}},[page,busy]);
 return <ProductContext.Provider value={product}>{notice&&<p className="product-notice" role="status">{notice}<button className="link-btn" onClick={()=>setNotice('')}>Dismiss</button></p>}{error&&<div className="transition-error" role="alert">{error}</div>}{busy&&<p className="opening-status" role="status">Opening your Folio…</p>}{controller?<AppShell/>:page==='welcome'?<WelcomeScreen/>:page==='help'||page==='about'?<main className="public-page"><button className="link-btn" onClick={()=>setPage(previous.current)}>Back</button>{page==='help'?<HelpScreen initialArticle={article}/>:<><h1>About Folio</h1><AboutFolio/></>}</main>:example?<main className="public-page"><h1>Example Profile</h1><p>Fictional, editable sample data. No password required.</p><button className="btn btn-primary" disabled={busy} onClick={()=>void enter()}>Explore Example Profile</button><button className="btn btn-secondary" onClick={product.openWelcome}>Welcome to Folio</button></main>:<ProfileGate/>}</ProductContext.Provider>;
}
